### PR TITLE
Adding pylint-odoo hook to pre-commit

### PR DESCRIPTION
**Pull request by ygol**
- Add pylint and/or pylint-odoo hook for pre-commit.

- small syntax change for chmod to be compatible with OSX

### CODE REVIEW

**Comment by blaggacao** [comment]
@ygol I finally had a look at the pylint check, looks good so far, but don't you think we should provide a .pylintrc file which ensures that pylint won't conflict with bugbear/flake8? Like only caring for the Odoo stuff of pylint-odoo + excluding the vendor directories like in `.flake8`?

**Comment by blaggacao** [comment]
If you have time you cold carve out the Mac/OSX fixes to merge already...

**Comment by ygol** [comment]
@blaggacao I think we could/should leave the .pylintrc out of this merge and let user choose what they want specifically included or not. I've added instruction within the code.

**Comment by blaggacao** [comment]
@ygol That's true, my main concern is that the default would conflict with flake8 somewhere or with odoo's code base itself.
This would lead to the situation where the first thing you'd have to do every time after you initialize a repo is to "fix" pylintrc. Am I missing something? False assumptions?
There are people initializing repos quite frequently as it seems.

**Comment by blaggacao** [comment]
#15 #14

**Pull request closed without merging**
