### PR TITLE
[REF] refactoring all hack/* scripts from bash to python.

### PR DESCRIPTION
**Pull request by shepilov-vladislav**

### CODE REVIEW

**Comment by shepilov-vladislav** [comment]
@blaggacao Resolved, now able to merge.

**Comment by blaggacao** [comment]
Merged [with small changes](https://github.com/xoe-labs/dockery-odoo-scaffold/commit/fcb18ea159bcebdb9bdb10a52605e250fc3b0ffa). Thank you!

**Comment by blaggacao** [comment]
I have noticed a problem with the patch apply machinery, I digging into it...

**Comment by blaggacao** [comment]
Look at how I manage patches for odoo (to free myself): https://github.com/xoe-labs/odoo-dev/branches

**Comment by blaggacao** [comment]
Done by the `odoo_dev.py`

**Comment by shepilov-vladislav** [comment]
> Look at how I manage patches for odoo (to free myself): https://github.com/xoe-labs/odoo-dev/branches

Ok, will see and debug it.

**Pull request merged**
